/*
    Each new term in the Fibonacci sequence is generated by adding the
    previous two terms. By starting with 1 and 2, the first 10 terms will be:

        1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

    By considering the terms in the Fibonacci sequence whose values do not
    exceed four million, find the sum of the even-valued terms.

    Date:   5/15/2016
    Author: Jeremiah Burley
 */
package solutions;

public class PE002 {

    public static void main(String[] args) {

        // Define Local Variables
        int newTerm = 1;
        int term1   = 1;
        int term2   = 2;
        int sum     = 2;	// First even Fibonacci number
        
        while (newTerm <= 4000000) {
        
        	newTerm = term1 + term2;
            
            if (newTerm % 2 == 0 && newTerm <= 4000000) {
            	sum += newTerm;
            }

        	term1 = term2;
        	term2 = newTerm;
        }
        System.out.print("\nThe sum of even-valued terms less than 4,000,000 is: " + sum);
    }
}